"use client";
import { gapLabels, initialQueueFilters, type AssignmentGap, type QueueFilters } from './review-queue';
import { STATE_NAME_BY_CODE } from './tax-body-policy';
export function QueueControls({ filters, onChange }: { filters: QueueFilters; onChange: (filters: QueueFilters) => void }) {
  return <section className="review-decision" aria-label="Review queue filters"><div className="review-form-grid">
    <label>State<select value={filters.state} onChange={e=>onChange({...filters,state:e.target.value})}><option value="all">All states</option>{[...STATE_NAME_BY_CODE].sort((a,b)=>a[1].localeCompare(b[1])).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label>
    <label>Minimum affected ship-tos<select value={filters.minimum} onChange={e=>onChange({...filters,minimum:Number(e.target.value)})}>{[0,1,10,50,100,500].map(n=><option key={n} value={n}>{n===0?'Any count':`${n} or more`}</option>)}</select></label>
    <label>Queue items<select value={filters.kind} onChange={e=>onChange({...filters,kind:e.target.value as QueueFilters['kind']})}><option value="all">Rates and unchecked assignments</option><option value="rates">Rate findings</option><option value="assignments">Unchecked assignments</option></select></label>
    <label>Evidence<select value={filters.evidence} onChange={e=>onChange({...filters,evidence:e.target.value as QueueFilters['evidence']})}><option value="all">Current and stale</option><option value="current">Current checks</option><option value="stale">Retained stale rate findings</option></select></label>
    <label>Assignment reason<select value={filters.reason} onChange={e=>onChange({...filters,reason:e.target.value})}><option value="all">All reasons</option>{Object.entries(gapLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
  </div><button className="secondary-button" type="button" onClick={()=>onChange(initialQueueFilters)}>Clear filters</button><p>Assignment reasons apply only to unchecked assignments. Retained stale rate findings are unverified; failed states do not supply current assignment counts.</p></section>;
}
export function AssignmentGapQueue({ gaps, onOpenState }: { gaps: AssignmentGap[]; onOpenState: (state: string)=>void }) {
  return <section className="queue-panel attention-panel" aria-labelledby="assignment-gap-title"><div className="panel-heading"><div><span className="section-label">Human investigation</span><h2 id="assignment-gap-title">Unchecked assignments</h2></div><span className="count-pill">{gaps.reduce((sum,gap)=>sum+gap.shipTos,0).toLocaleString()} ship-tos</span></div><p>These groups have no completed rate comparison. They are separate from rate discrepancies and deliberate no-tax assignments. Open the state to inspect its tax bodies and exclusions.</p>{gaps.length===0?<p>No assignment groups match these filters in the available checks. Unavailable state counts are unknown.</p>:gaps.map((gap,i)=><button className="history-card finding-card" type="button" key={`${gap.stateCode}-${gap.taxBody}-${gap.reason}-${i}`} onClick={()=>onOpenState(gap.stateCode)}><span className="status-mark comparison-not-checked">?</span><span><strong>{gapLabels[gap.reason]}</strong><small>{gap.stateCode} · {gap.taxBody ?? 'State aggregate; tax body not supplied'} · {gap.shipTos.toLocaleString()} ship-tos</small></span><span className="row-arrow" aria-hidden="true">›</span></button>)}</section>;
}
